// Generated by npm run sync. Do not edit by hand.

export type Resource = {
  id: string;
  title: string;
  kind: string;
  sourceUrl: string;
  added: string;
  status: string;
  topics: string[];
  summary: string;
  whySaved: string[];
  highlights: string[];
};

export const resources: Resource[] = [
  {
    "id": "agentic-design-patterns",
    "title": "Agentic Design Patterns: A Hands-On Guide to Building Intelligent Systems",
    "kind": "repository",
    "sourceUrl": "https://github.com/evoiz/Agentic-Design-Patterns",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering"
    ],
    "summary": "A third-party repository pairing a 424-page book PDF with Jupyter notebooks for 21 agentic-system patterns. Its scope runs from chaining, routing, parallel work, reflection, tools, planning, and multi-agent coordination through memory, adaptation, MCP, recovery, human oversight, RAG, inter-agent communication, optimization, reasoning, guardrails, evaluation, prioritization, and exploration.",
    "whySaved": [
      "Offers a broad taxonomy for reviewing an agent design.",
      "Maps conceptual chapters to many framework-specific notebook examples.",
      "Can serve as a curriculum outline or an index for finding a pattern to explore."
    ],
    "highlights": [
      "The inspected tree contains one PDF, two README files, and 65 notebooks.",
      "Examples span Google ADK, LangChain and LangGraph, CrewAI, FastMCP, Vertex AI, OpenEvolve, and other tools.",
      "The README proposes a read, run, modify, and combine workflow for studying the patterns."
    ]
  },
  {
    "id": "agentic-rl-workshop-part-1",
    "title": "AI Agent Workshop Tokyo 2026, Part 1: Agentic RL",
    "kind": "note",
    "sourceUrl": "https://github.com/nejumi/art-e-nano",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "reinforcement-learning"
    ],
    "summary": "An 84-page Japanese workshop deck that connects Agentic RL concepts to a lab for training an email-search agent over Enron mail. It frames an agent in terms of observations, actions, tools, rewards, and trajectories; develops an outcome-led reward design; and uses OpenPipe ART, W&B Serverless RL, W&B Training, and Weave for training and trace inspection. The later sections introduce GRPO and GSPO, rollout infrastructure, reward-hacking diagnosis, safety controls, checkpoint selection, and a staged adoption roadmap.",
    "whySaved": [
      "Bridges reinforcement-learning terminology and an executable agent environment.",
      "Uses trace-level debugging to explain IDK escape and reward hacking.",
      "Provides practical checklists for reward contracts, checkpoint gates, rollout observability, and tool safety."
    ],
    "highlights": [
      "Agentic RL optimizes a trajectory or way of working rather than only the quality of one response.",
      "Suitable tasks have tools, verifiable outcomes, reproducible environments, and obtainable failure logs. A full setup covers environment, tools, reward, rollout collection, and observability.",
      "Final-answer and source correctness should anchor reward; partial credit, penalties, and model judges should remain subordinate to the main outcome signal.",
      "The lab exposes search_emails, read_email, and return_final_answer; a result includes a source message ID or an explicit “I don't know.”"
    ]
  },
  {
    "id": "ai-agent-workshop-tokyo-auto-improvement",
    "title": "AI Agent Workshop Tokyo — AI Agent Auto Improvement",
    "kind": "note",
    "sourceUrl": "https://wandb.ai/site/resources/events/ai-agent-workshop-tokyo/",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "agent-evaluation"
    ],
    "summary": "A 38-page Japanese workshop deck presenting a W&B Weave-centered loop for continuously improving AI agents. It progresses from tracing and versioning a Discovery Agent through human annotation and coding-agent-assisted prompt changes, offline evaluation, production monitoring, trace analysis, and isolated execution.",
    "whySaved": [
      "Gives a concrete path from manual judgments to repeatable offline evaluation and production signals.",
      "Shows how a coding agent can consume traces and eval evidence before revising a prompt.",
      "Treats prompts, datasets, scorers, agent versions, and monitoring as connected artifacts."
    ],
    "highlights": [
      "W&B Skills and MCP can connect coding agents such as Claude Code and Codex to stored agent versions, evaluations, and usage data.",
      "The deck positions Weave as a harness for observability, versioning, offline evaluation, feedback, online evaluation, and deployment, with versioned Prompt, Dataset, Scorer, and Model objects.",
      "Agent evaluation should grow from initial human judgments because early systems may lack data and clear criteria.",
      "Human feedback from an annotation queue can become input to a skill that revises an agent prompt."
    ]
  },
  {
    "id": "archify",
    "title": "Archify",
    "kind": "tool",
    "sourceUrl": "https://tt-a1i.github.io/archify/",
    "added": "2026-08-14",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "developer-tools",
      "visualization"
    ],
    "summary": "An agent skill and local renderer for turning a system description or codebase analysis into an interactive technical diagram. Archify supports architecture, workflow, sequence, data-flow, and lifecycle views using typed JSON source, deterministic validation, and self-contained HTML output. The generated viewer can expose authored routes, reachability, guided stories, and source evidence, with static and motion export formats for sharing or review.",
    "whySaved": [
      "Produces inspectable diagram source and validation results rather than only a generated image.",
      "Covers several technical storytelling modes with one agent-facing workflow.",
      "Creates portable HTML artifacts that can be refined conversationally and shared without a hosted service."
    ],
    "highlights": [
      "The skill supports Raven, Cursor, Claude Code, Codex CLI, and OpenCode.",
      "Its five diagram modes are Architecture, Workflow, Sequence, Data Flow, and Lifecycle; Architecture Delta can compare validated before-and-after sources.",
      "Schema, layout, HTML/SVG, route, and label-clearance checks run before a showcase artifact replaces the last verified output.",
      "Generated artifacts can include semantic search, exact authored route and reachability inspection, guided views, themes, and finite motion."
    ]
  },
  {
    "id": "cmux",
    "title": "cmux",
    "kind": "tool",
    "sourceUrl": "https://cmux.com/",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "developer-tools"
    ],
    "summary": "A free, open-source native macOS terminal designed for multitasking across coding agents. Built with Swift, AppKit, and libghostty, it combines vertical workspaces, split panes, contextual notifications, an embedded programmable browser, remote workflows, and a CLI and Unix-socket API. cmux presents these as composable terminal primitives rather than prescribing one agent orchestrator, so existing command-line agents and Ghostty configuration can remain part of the workflow.",
    "whySaved": [
      "Makes parallel agent sessions visible and shows which pane needs attention.",
      "Places a scriptable browser beside the terminal for web-development verification.",
      "Exposes workspace, pane, terminal, and browser operations to automation."
    ],
    "highlights": [
      "Workspaces can display Git branch, pull-request state, working directory, ports, and recent notification text; attention signals come from terminal escape sequences, the cmux CLI, or agent hooks.",
      "Its browser API supports navigation, DOM snapshots, interaction, JavaScript evaluation, and console and network inspection.",
      "It supports SSH workspaces and remote tmux attachment, though the latter is labeled beta.",
      "cmux currently requires macOS 14 or later. Session restore preserves app-owned layout and metadata but does not checkpoint arbitrary live processes; the iOS companion is also beta."
    ]
  },
  {
    "id": "database-design-course",
    "title": "Database Design Course",
    "kind": "video",
    "sourceUrl": "https://www.youtube.com/watch?v=ztHopE5Wnpc",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "databases"
    ],
    "summary": "An eight-hour introductory course by Caleb Curry on planning relational databases. It develops a working vocabulary for databases and SQL, then spends most of its time on relationships, keys, entity-relationship modeling, normalization, indexes, data types, and joins.",
    "whySaved": [
      "Provides one continuous path from basic database concepts to schema design.",
      "Gives extended treatment to relationship modeling and the tradeoffs among key types.",
      "Uses normalization and joins to connect logical design with query behavior."
    ],
    "highlights": [
      "Database design organizes stored data and its relationships according to a data model.",
      "The course distinguishes one-to-one, one-to-many, and many-to-many relationships and demonstrates how to represent each with tables and keys.",
      "Its key section covers primary, alternate, natural, surrogate, foreign, simple, composite, and compound keys, including constraints and selection tradeoffs.",
      "Later sections introduce entity-relationship cardinality and modality, the first three normal forms, clustered and nonclustered indexes, and several join forms."
    ]
  },
  {
    "id": "demystifying-evals-for-ai-agents",
    "title": "Demystifying evals for AI agents",
    "kind": "article",
    "sourceUrl": "https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "agent-evaluation"
    ],
    "summary": "Anthropic's practical framework for evaluating multi-turn, tool-using agents. It defines an agent eval's tasks, trials, graders, transcripts, and outcomes; compares deterministic, model-based, and human grading; distinguishes capability from regression suites; and gives an incremental roadmap for building and maintaining evaluations.",
    "whySaved": [
      "Turns agent evaluation into an implementable product-engineering practice.",
      "Explains how task ambiguity, harness constraints, grading bugs, and exploitable loopholes can invalidate a reassuring score.",
      "Adapts evaluation design to coding, conversational, research, and computer-use agents."
    ],
    "highlights": [
      "Evaluate the model and agent harness together, including transcripts and the final state of the environment.",
      "Prefer deterministic grading when outcomes permit it, and combine code, model, and human graders according to the task.",
      "Capability suites should remain difficult enough to show progress; regression suites should be near-perfect so they expose backsliding.",
      "pass@k measures whether at least one of several trials succeeds, while pass^k measures whether all trials succeed consistently."
    ]
  },
  {
    "id": "dotenvx",
    "title": "dotenvx",
    "kind": "repository",
    "sourceUrl": "https://github.com/dotenvx/dotenvx",
    "added": "2026-08-14",
    "status": "reference",
    "topics": [
      "developer-tools",
      "secrets-management",
      "environment-configuration"
    ],
    "summary": "A cross-platform tool and library for loading environment variables, managing multiple .env files, and encrypting their values. It can wrap commands for applications written in many languages, integrate with frameworks and CI/CD, and keep encrypted environment files separate from the private keys required to decrypt them.",
    "whySaved": [
      "Extends the familiar dotenv workflow beyond a single language or framework.",
      "Supports explicit composition of multiple environments and override behavior.",
      "Provides encryption, validation, example-file generation, and secret-output redaction in one command-line workflow.",
      "Includes documented integrations for coding agents, containers, deployment platforms, password managers, and common application frameworks."
    ],
    "highlights": [
      "dotenvx run -- <command> injects variables from .env files into any child process, independent of the application's language.",
      "Multiple environment files can be loaded in a declared order; --overload changes whether later files override values already set.",
      "dotenvx encrypt produces an encrypted .env file and a separate public and private key pair. Deployment requires the corresponding DOTENV_PRIVATE_KEY rather than storing that private key beside the encrypted file.",
      "The CLI can validate environment files against .env.example, generate an example file, and redact secret values from wrapped command output."
    ]
  },
  {
    "id": "fast-ai",
    "title": "fast.ai",
    "kind": "web",
    "sourceUrl": "https://www.fast.ai/",
    "added": "2026-08-12",
    "status": "reference",
    "topics": [
      "deep-learning",
      "artificial-intelligence",
      "ai-education"
    ],
    "summary": "A practical deep-learning education and software hub. The site brings together fast.ai's courses, the fastai library for PyTorch, nbdev, the Practical Deep Learning for Coders book, and a long-running blog covering technical work, education, advice, health, and AI's societal effects.",
    "whySaved": [
      "Provides a code-first route into deep learning through courses, software, and worked examples.",
      "Keeps practical engineering material alongside writing about education and the social consequences of AI.",
      "Serves as a stable starting point for discovering fast.ai's current projects without splitting the site into separate resources."
    ],
    "highlights": [
      "The homepage currently points readers to Practical Deep Learning for Coders and How to Solve It With Code.",
      "Its software links include the fastai library for PyTorch and nbdev.",
      "The blog is organized across advice, AI in society, courses, education, health, and technical topics."
    ]
  },
  {
    "id": "grill-me",
    "title": "Grill Me",
    "kind": "tool",
    "sourceUrl": "https://github.com/mattpocock/skills/tree/main/skills/productivity/grill-me",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "agent-skills"
    ],
    "summary": "A stateless agent skill for turning a loose idea, plan, or decision into an explicit design tree. It asks dependency-aware questions in rounds, recommends an answer for each, incorporates the user's decisions, and stops before execution until both sides confirm shared understanding. The skill is intended for explicit invocation and can be used for software, products, writing, business decisions, or other planning subjects without requiring a repository.",
    "whySaved": [
      "Exposes assumptions and unresolved branches before implementation begins.",
      "Orders questions by dependency instead of presenting a generic questionnaire.",
      "Leaves decisions with the user while assigning environmental research to the agent."
    ],
    "highlights": [
      "Each round contains the current question frontier: all questions whose prerequisites are resolved. Each question includes a recommended answer.",
      "The wrapper delegates its interview logic to a separate grilling skill.",
      "It writes no files; the result exists in the conversation and the participants' shared understanding.",
      "Broad scopes can create long sessions, and questions requiring runnable or visual evidence are better handled through prototypes."
    ]
  },
  {
    "id": "grill-with-docs",
    "title": "Grill with Docs",
    "kind": "tool",
    "sourceUrl": "https://github.com/mattpocock/skills/tree/main/skills/engineering/grill-with-docs",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "agent-skills"
    ],
    "summary": "A stateful planning skill that combines a dependency-aware grilling interview with repository-aware domain modeling. As terminology and consequential choices become clear, it checks them against the codebase and records canonical vocabulary in CONTEXT.md files and qualifying architectural decisions in ADRs. It is designed for planning that should leave a narrow, durable paper trail rather than only conversational agreement.",
    "whySaved": [
      "Keeps planning vocabulary aligned with the repository being changed.",
      "Preserves settled domain language for future collaborators and agents.",
      "Uses a high threshold for ADRs so ordinary implementation choices do not become permanent documentation."
    ],
    "highlights": [
      "The wrapper depends on separate grilling and domain-modeling skills; installing the wrapper alone does not provide a working workflow.",
      "Vocabulary is written as it is resolved. ADRs are offered only for decisions that are hard to reverse, surprising without context, and genuine tradeoffs.",
      "It mutates the repository and is intended for work resolvable in one session.",
      "The documentation warns about drift with multiple curators and a failure mode in some orchestration contexts where the interview runs but writes do not occur."
    ]
  },
  {
    "id": "herdr",
    "title": "Herdr",
    "kind": "tool",
    "sourceUrl": "https://herdr.dev/",
    "added": "2026-08-11",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "developer-tools"
    ],
    "summary": "An open-source, terminal-native multiplexer for running several coding agents at once. Herdr keeps real terminal processes alive in a background server, organizes them into workspaces, tabs, and panes, tracks agent state, and supports local, SSH, and thin-client attachment without replacing the user's terminal emulator. It also exposes CLI and local socket APIs so scripts or other agents can create layouts, control panes, prompt recognized agents, inspect output, and wait for lifecycle changes.",
    "whySaved": [
      "Keeps agent sessions and their processes running across terminal disconnects.",
      "Makes blocked, working, done, and idle agents visible across several projects.",
      "Supports remote and phone-sized terminal workflows without a browser dashboard or hosted control plane.",
      "Gives agents a structured automation surface instead of relying only on raw keystrokes."
    ],
    "highlights": [
      "A background server owns persistent PTYs while one or more terminal clients can attach, detach, and reconnect locally or over SSH.",
      "Agent state rolls up from panes to tabs and workspaces, helping users jump to the session that needs attention.",
      "The CLI and JSON socket API distinguish layout management, raw pane control, and recognized-agent operations such as start, prompt, send keys, and wait.",
      "Herdr detects common agent CLIs including Claude Code, Codex, OpenCode, Cursor, Copilot, and others. Unsupported agents still run as terminal processes, but richer state and session behavior may require a supported integration."
    ]
  },
  {
    "id": "hitchhikers-guide-to-agentic-ai",
    "title": "The Hitchhiker's Guide to Agentic AI: From Foundations to Systems",
    "kind": "paper",
    "sourceUrl": "https://arxiv.org/abs/2606.24937",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "reinforcement-learning",
      "model-training",
      "model-evaluation"
    ],
    "summary": "Haggai Roitman's book-length practitioner reference traces a path from transformer, GPU, optimization, and reinforcement-learning foundations to aligned models, reasoning systems, and production agents. Its 30 chapters then cover evaluation, RAG, memory, agent harnesses, loop engineering, design patterns, environments, MCP, agent skills, A2A communication, multi-agent architectures, frameworks, interfaces, assessment questions, and a compact reference section. This is a broad educational synthesis rather than a conventional empirical paper. Its central position is that agent quality depends on the entire pipeline - model, training, systems, orchestration, tools, memory, evaluation, security, and deployment.",
    "whySaved": [
      "Provides one map across model training, systems engineering, and agent architecture.",
      "Pairs intuition and mathematical foundations with code, diagrams, design choices, debugging guidance, and failure modes.",
      "Offers a useful index into the primary literature through 443 bibliography entries.",
      "Includes 108 review questions and a quick-reference section for later retrieval."
    ],
    "highlights": [
      "The guide is organized into six parts: foundations; RL methods for LLMs; reasoning; evaluation; agentic AI; and assessment and reference.",
      "Its RL material covers PPO, DPO, GRPO, preference-optimization variants, reward modeling, SFT, large-scale training systems, and trajectory-level agent training.",
      "The evaluation chapter separates model and agent tasks and discusses human annotation, ranking and generation metrics, task success, trajectory efficiency, tool-use accuracy, model judges, contamination, and Goodhart's law.",
      "The agentic section treats the harness as a runtime layer responsible for reasoning coordination, tool execution, memory, communication, observability, and safety rather than as a thin prompt wrapper."
    ]
  },
  {
    "id": "ilya-30u30",
    "title": "Ilya 30u30",
    "kind": "collection",
    "sourceUrl": "https://arc.net/folder/D0472A20-9C20-4D3F-B145-D2865C0A9FEE",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "artificial-intelligence",
      "deep-learning"
    ],
    "summary": "A public Arc folder collecting foundational material about neural networks and deep learning. Its scope moves across learning and complexity, convolutional and recurrent networks, attention, transformers, memory and relational reasoning, scaling, and machine intelligence. The folder currently presents 27 linked resources. It is intentionally tracked here as one collection resource; the individual links are not separate records.",
    "whySaved": [
      "A compact path through several foundations of modern deep learning.",
      "A useful source for choosing a longer-term reading sequence.",
      "Connects theoretical ideas such as description length and complexity with influential neural-network architectures."
    ],
    "highlights": []
  },
  {
    "id": "inside-openais-in-house-data-agent",
    "title": "Inside OpenAI's in-house data agent",
    "kind": "article",
    "sourceUrl": "https://openai.com/index/inside-our-in-house-data-agent/",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "agent-evaluation"
    ],
    "summary": "OpenAI describes an internal data agent that turns natural-language questions into data discovery, warehouse queries, analysis, and cited results. The article focuses less on model prompting than on the surrounding context system: schemas, query history, human annotations, code, company knowledge, memory, live runtime state, permissions, and evaluation.",
    "whySaved": [
      "Shows the context infrastructure behind a production data agent.",
      "Gives a concrete example of evaluating generated SQL by executing it and grading both the query and returned data.",
      "Records design lessons about tool count, goal-oriented guidance, permissions, transparency, and learning meaning from code."
    ],
    "highlights": [
      "OpenAI reports that its internal data platform serves about 3,500 users across roughly 600 petabytes and 70,000 datasets.",
      "The GPT-5.2-powered agent is exposed through Slack, the web, IDEs, Codex CLI via MCP, and an MCP connector in OpenAI's internal ChatGPT.",
      "Its context combines platform metadata and historical queries, human annotations, code-derived knowledge, permission-aware institutional knowledge, memory, and live runtime state. Offline context is normalized and indexed; warehouse data is queried live when needed.",
      "Evals use curated questions with reference SQL. The system executes generated SQL and compares both the SQL and result data with the reference using an eval grader."
    ]
  },
  {
    "id": "knip",
    "title": "Knip",
    "kind": "tool",
    "sourceUrl": "https://knip.dev/",
    "added": "2026-08-24",
    "status": "reference",
    "topics": [
      "developer-tools",
      "static-analysis",
      "javascript-typescript"
    ],
    "summary": "A static-analysis and cleanup tool for JavaScript and TypeScript projects. Knip starts from project entry files, follows imports to build a reachability graph, and reports unused files, exports, and dependencies as well as dependencies used but missing from package metadata. Framework and tooling plugins supply convention-specific entry points, making the same analysis usable across applications, libraries, workspaces, and monorepos.",
    "whySaved": [
      "Finds repository-level dead code that file-local linters do not see.",
      "Checks source reachability and package metadata in one pass.",
      "Supports gradual adoption, CI enforcement, and reviewed automatic fixes."
    ],
    "highlights": [
      "Knip builds its graph from entry files, resolved imports, configuration and shell-script references, and compiled views of non-standard files such as Vue and Svelte components.",
      "Plugins add entry points for supported frameworks and tools; the documentation currently lists more than 180 plugins.",
      "Version 6 requires Node.js 20.19 or newer, or Bun, and can be installed through npm, pnpm, Bun, or Yarn.",
      "Auto-fix can remove unused exports, dependencies, catalog entries, and other supported findings. File deletion additionally requires --allow-remove-files, and the documentation advises using version control to review and undo changes."
    ]
  },
  {
    "id": "l8-principals-agentic-engineering-workflow",
    "title": "L8 Principal's Agentic Engineering Workflow",
    "kind": "video",
    "sourceUrl": "https://www.youtube.com/watch?v=iQyg-KypKAA",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering"
    ],
    "summary": "Kun Chen presents a terminal-centered workflow for scaling coding-agent work from one supervised session to multiple isolated agents and, finally, an orchestrating “first mate.” The walkthrough combines environment ergonomics, compact memory files, progressively disclosed skills, interactive planning, automated validation, long-running loops, Git worktrees, and risk-based human review. The central idea is to spend human attention at the beginning and end of a task: clarify intent and requirements first, let agents handle the implementation and verification loop, then apply judgment to evidence, risk, and product impact.",
    "whySaved": [
      "A concrete example of an end-to-end agentic software-engineering workflow.",
      "Practical guidance on controlling context, parallel work, and validation rather than focusing only on prompting.",
      "A useful reference for deciding what should remain human-led as agent throughput increases."
    ],
    "highlights": [
      "Chen favors a keyboard-first stack built around WezTerm, tmux, and Neovim, but says the underlying workflow is intended to remain usable with other interfaces and agent harnesses (02:10, 09:21).",
      "Global memory should stay minimal because it is loaded into every session; project memory can accumulate repository-specific conventions and corrections. Conditionally useful instructions should move into skills so they are loaded only when relevant (11:24, 14:50, 16:12).",
      "Skills from untrusted sources create security risk, and popularity alone does not demonstrate that a skill improves agent performance. The video recommends preferring evaluated, task-specific skills over broad promises of automatic improvement (18:40).",
      "The workflow uses voice input and tools designed for agent efficiency, then an interactive HTML artifact for planning so requirements and alternatives can be reviewed visually before implementation (20:27, 22:12, 24:25)."
    ]
  },
  {
    "id": "lets-reproduce-gpt-2-124m",
    "title": "Let's reproduce GPT-2 (124M)",
    "kind": "video",
    "sourceUrl": "https://www.youtube.com/watch?v=l8pRSuU81PU&ab_channel=AndrejKarpathy",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "deep-learning",
      "model-training"
    ],
    "summary": "Andrej Karpathy implements and trains the 124-million-parameter GPT-2 model from scratch. The four-hour walkthrough moves from reconstructing the architecture and loading the published checkpoint through GPU optimization, training configuration, distributed execution, validation, and comparison with the original model.",
    "whySaved": [
      "Connects transformer equations and model structure to working PyTorch code.",
      "Shows how mixed precision, compilation, fused operations, Flash Attention, and distributed training change a real training loop.",
      "Treats validation and HellaSwag evaluation as part of the build, not an afterthought."
    ],
    "highlights": [
      "The implementation covers embeddings, transformer blocks, parameter sharing, initialization, batching, cross-entropy loss, and autoregressive sampling.",
      "The optimization section discusses Tensor Cores, TF32, bfloat16, torch.compile, kernel fusion, Flash Attention, and vocabulary-size alignment.",
      "The training section derives choices such as AdamW, gradient clipping, warmup plus cosine decay, gradient accumulation, and distributed data parallelism from the GPT-2 and GPT-3 setup.",
      "The run uses FineWeb EDU data, a held-out validation split, and HellaSwag before comparing the resulting model with the published GPT-2 checkpoint."
    ]
  },
  {
    "id": "llm-evaluation-guidebook",
    "title": "The LLM Evaluation Guidebook",
    "kind": "web",
    "sourceUrl": "https://huggingface.co/spaces/OpenEvals/evaluation-guidebook",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "model-evaluation"
    ],
    "summary": "A Hugging Face guide to interpreting and designing language-model evaluations. It covers tokenization and inference details that change scores, benchmark selection, saturation and contamination, evaluation during training ablations, custom automated tasks, human annotation, model judges, and reproducibility.",
    "whySaved": [
      "Teaches how to interrogate an evaluation result instead of treating a leaderboard score as a complete capability claim.",
      "Gives concrete criteria for selecting tasks that produce useful training signal.",
      "Connects benchmark design with human annotation, model-judge calibration, and environment-level reproducibility."
    ],
    "highlights": [
      "Model builders need fast, discriminative tasks that can be repeated during ablations, while model users need tasks close to their intended use cases.",
      "Scores measure performance on particular samples and proxies, not a model's global superiority at a capability.",
      "Chat templates, reasoning traces, tokenization, inference formulation, prompts, normalization, generation settings, and metrics can all alter results.",
      "The guide's pretraining example selects tasks using above-random performance, monotonic learning signal, low seed noise, and stable model ordering."
    ]
  },
  {
    "id": "marcos-hernanz-side-project-agents-md",
    "title": "Marcos Hernanz's Side-Project AGENTS.md",
    "kind": "web",
    "sourceUrl": "https://x.com/MarcosHernanz/status/2083954734487212511",
    "added": "2026-08-13",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "agent-instructions",
      "software-design"
    ],
    "summary": "An X post in which Marcos Hernanz shares a compact AGENTS.md developed after extensive agent use. Its rules favor simple implementations for current needs, incremental end-to-end development, modular components, established libraries, existing project dependencies, durable architecture, and learning from proven products before designing a new solution. The post also takes a deliberately aggressive stance against backward-compatibility layers. Hernanz adds an explicit follow-up warning that he uses these instructions only for side projects and does not recommend applying them uncritically in production.",
    "whySaved": [
      "Offers a short example of encoding software-design preferences in repository-level agent instructions.",
      "Provides useful prompts for discussing simplicity, reuse, modularity, and incremental delivery with coding agents.",
      "Includes an important reminder that effective instructions are contextual and can become destructive when copied into a different environment."
    ],
    "highlights": [
      "Hernanz says the shared file reflects experience from roughly 60 billion tokens of agent use.",
      "The attached instructions emphasize the simplest complete solution, growing a working system in layers, clear separation of concerns, and established dependencies over unnecessary custom code.",
      "A follow-up adds the principle of studying how established products solve a problem and adopting proven patterns where appropriate.",
      "The author explicitly limits this setup to side projects and warns against treating it as production guidance."
    ]
  },
  {
    "id": "no-mistakes",
    "title": "git push no-mistakes",
    "kind": "tool",
    "sourceUrl": "https://github.com/kunchenguid/no-mistakes",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "developer-tools"
    ],
    "summary": "An open-source local Git quality gate for agent-generated changes. Instead of pushing directly to the real remote, a branch is sent through a proxy remote that runs review, tests, documentation, and lint checks in a disposable worktree. It forwards the branch and opens a pull request only after the configured gates pass. The same pipeline can be driven through Git, an interactive TUI, or a coding-agent skill. Mechanical fixes can be applied automatically, while findings that affect intent remain human decisions.",
    "whySaved": [
      "Adds a repeatable quality boundary between coding agents and the remote branch.",
      "Keeps validation and repair work isolated from the active checkout.",
      "Offers a concrete model for automating routine review without delegating product judgment."
    ],
    "highlights": [
      "The pipeline covers review, testing, documentation, linting, push, pull-request creation, and CI monitoring in a disposable worktree.",
      "Entry points are git push no-mistakes, the no-mistakes TUI, and a /no-mistakes agent skill. Several coding-agent runners are supported.",
      "A runnable agent and provider-specific tooling or credentials are required for the complete workflow. Installation also runs a background daemon.",
      "Official release binaries enable the project's self-hosted telemetry by default; it can be disabled with NO_MISTAKES_TELEMETRY=0."
    ]
  },
  {
    "id": "ponytail",
    "title": "Ponytail",
    "kind": "tool",
    "sourceUrl": "https://github.com/dietrichgebert/ponytail",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "agent-skills",
      "developer-tools"
    ],
    "summary": "An open-source, cross-harness agent policy and skill collection intended to reduce overengineering. Before adding code, it asks whether the feature is necessary, already exists, can use the standard library or native platform, can reuse an installed dependency, or can be expressed more simply. The project explicitly keeps validation, data-loss handling, security, and accessibility outside the scope of simplification. It also provides commands for reviewing diffs or repositories for unnecessary complexity.",
    "whySaved": [
      "Provides a concrete decision ladder for countering agent overbuilding.",
      "Supports multiple coding-agent hosts through plugins, skills, or instruction files.",
      "Publishes benchmark methods and corrections rather than presenting only a headline."
    ],
    "highlights": [
      "The decision ladder prioritizes YAGNI, reuse, the standard library, native platform features, installed dependencies, and only then minimal custom code.",
      "Project-reported agentic benchmarks on 12 feature tasks with Haiku 4.5 found 54% fewer changed lines, 22% fewer tokens, 20% lower cost, and 27% less time while retaining all tested safety guards. These results were not independently verified.",
      "The effect varied by task and model; the repository corrects an older headline that overstated the typical reduction.",
      "Full plugin behavior can require Node-based lifecycle hooks, while support and command availability differ across agent hosts."
    ]
  },
  {
    "id": "smol-training-playbook",
    "title": "The Smol Training Playbook: The Secrets to Building World-Class LLMs",
    "kind": "web",
    "sourceUrl": "https://huggingface.co/spaces/HuggingFaceTB/smol-training-playbook",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "deep-learning",
      "model-training"
    ],
    "summary": "A Hugging Face case study and practical guide to developing SmolLM3, a three-billion-parameter multilingual reasoning model trained on 11 trillion tokens. It spans the decision to train, architecture and data experiments, small-scale ablations, long-running pretraining, post-training, evaluation, and GPU-cluster operations.",
    "whySaved": [
      "Connects model-training recipes to the failed experiments, restarts, debugging, and infrastructure work usually absent from papers.",
      "Gives concrete criteria for designing and interpreting small-scale ablations.",
      "Treats evaluation, telemetry, checkpointing, and recovery as part of the training system."
    ],
    "highlights": [
      "Before training from scratch, the guide recommends testing whether prompting or fine-tuning an existing open model can satisfy the use case.",
      "Architecture choices should begin from a documented design supported by both the intended training and inference frameworks.",
      "Ablations should be fast but discriminative, change one variable at a time, keep parameter counts comparable, and validate promising proxy results at a larger or more production-like scale.",
      "Post-training begins by defining evaluations, then iterates through supervised fine-tuning, preference optimization, and, where useful, on-policy reinforcement learning."
    ]
  },
  {
    "id": "stanford-cs336-language-modeling-from-scratch",
    "title": "Stanford CS336: Language Modeling from Scratch",
    "kind": "course",
    "sourceUrl": "https://cs336.stanford.edu/",
    "added": "2026-08-18",
    "status": "reference",
    "topics": [
      "deep-learning",
      "language-models",
      "systems"
    ],
    "summary": "An advanced Stanford course on building language models across the full development pipeline. The Spring 2026 offering moves from tokenization, Transformer components, and training into GPU kernels, distributed systems, scaling laws, inference, evaluation, pretraining data, supervised fine-tuning, reinforcement learning, and alignment. The public course site keeps the syllabus, lecture materials, recordings, and five substantial programming assignments together as one implementation-driven curriculum.",
    "whySaved": [
      "Connects model architecture and training theory to the systems engineering required to run language models efficiently.",
      "Provides assignment code for implementing core components rather than only using high-level training libraries.",
      "Covers the complete lifecycle from raw pretraining data through evaluation and post-training."
    ],
    "highlights": [
      "Tatsunori Hashimoto and Percy Liang teach the Spring 2026 offering.",
      "Assignment 1 implements a tokenizer, Transformer architecture, optimizer, and minimal training run.",
      "Later assignments cover profiling and Triton FlashAttention2, memory-efficient distributed training, scaling laws, Common Crawl filtering and deduplication, and supervised fine-tuning plus reinforcement learning for math reasoning.",
      "The course assumes strong Python and software-engineering ability, PyTorch and systems-optimization experience, linear algebra, probability, and prior machine learning or deep-learning knowledge."
    ]
  },
  {
    "id": "vite-plus",
    "title": "Vite+",
    "kind": "tool",
    "sourceUrl": "https://viteplus.dev/",
    "added": "2026-08-14",
    "status": "reference",
    "topics": [
      "developer-tools",
      "web-development"
    ],
    "summary": "An open-source web-development toolchain exposed through the vp command. It combines runtime and package-manager management with Vite and Rolldown builds, Vitest, Oxlint, Oxfmt, tsdown packaging, and cached task orchestration. Vite+ aims to replace a collection of separately configured local tools with one command surface and a shared vite.config.ts, while retaining the Vite plugin and framework ecosystem.",
    "whySaved": [
      "Offers consistent development, checking, testing, building, and task commands across projects and teams.",
      "Can use npm, pnpm, Yarn, or Bun rather than imposing a new package manager.",
      "Provides migration tooling for consolidating an existing Vite-based setup."
    ],
    "highlights": [
      "vp dev, vp check, vp test, vp build, vp pack, and vp run cover the main local development lifecycle, while vp env and dependency commands manage Node.js and the selected package manager.",
      "The integrated stack includes Vite, Rolldown, Vitest, Oxlint, Oxfmt, tsdown, and Vite Task, with support for frameworks built on Vite.",
      "vp migrate can update dependencies, rewrite imports, merge tool-specific configuration, update scripts, and optionally add hooks or agent instructions.",
      "Vite+ is MIT-licensed and currently in beta. Its maintainers describe it as stable but not feature-complete on the path to 1.0."
    ]
  },
  {
    "id": "wait-what",
    "title": "Wait What",
    "kind": "tool",
    "sourceUrl": "https://github.com/mattpocock/skills/tree/main/skills/productivity/wait-what",
    "added": "2026-08-11",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "agent-skills"
    ],
    "summary": "A small, explicitly invoked agent skill for recovering when an explanation did not land. It asks the agent to re-pitch its previous message with enough context, ASD-STE100 Simplified Technical English, and the project-specific vocabulary in CONTEXT.md.",
    "whySaved": [
      "Provides a reusable reset when an agent response is too compressed or assumes context the reader does not have.",
      "Requests simpler language without discarding the terminology already agreed in the project.",
      "Packages a common conversational correction into a short explicit command."
    ],
    "highlights": [
      "The skill is configured for explicit use rather than automatic invocation.",
      "Its instruction applies to the immediately preceding response and asks for a new explanation, not a continuation.",
      "The re-pitch should add context, use simplified technical English, and reuse the ubiquitous language recorded in CONTEXT.md."
    ]
  },
  {
    "id": "warp",
    "title": "Warp",
    "kind": "tool",
    "sourceUrl": "https://www.warp.dev/",
    "added": "2026-08-08",
    "status": "reference",
    "topics": [
      "agentic-engineering",
      "developer-tools"
    ],
    "summary": "A cross-platform agentic development environment built around a modern terminal. Warp combines a block-based command interface, code editing and review, built-in local and cloud agents powered by Oz, and enhanced interfaces for third-party CLI agents. Its client is open source, while its hosted AI and orchestration services use Warp's separate cloud platform.",
    "whySaved": [
      "Brings terminal commands, agent conversations, code diffs, and reviews into one interface.",
      "Provides a control surface for running and monitoring several local or cloud agents.",
      "Enhances third-party CLI agents such as Claude Code, Codex, and OpenCode without requiring a switch to a conventional IDE."
    ],
    "highlights": [
      "Warp offers terminal and agent modes, block-based command navigation, multiline editing, syntax highlighting, completions, a file tree, LSP-assisted editing, and interactive code review.",
      "Local agents can run terminal commands, edit code, use attached files, images, URLs, and selections, consult MCP servers and shared context, and surface task lists and diffs for review.",
      "Oz extends the model to programmable cloud agents that can run concurrently from triggers, schedules, integrations, an SDK, or a CLI, with activity tracking and auditability.",
      "Warp supports macOS, Windows, and Linux on both x86-64 and ARM64 where documented."
    ]
  }
];
